version: 2.1

workflows:
  pipeline:
    jobs:
      - build:
          context:
            - Docker Hub

jobs:
  build:
    docker:
      - image: "circleci/node:9.6.1"
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout
      - run: |
          cd src/FinanceAPI
          docker build -t $DOCKERHUB_USERNAME/finance-api:latest .
