<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Bson" Version="3.0.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.0.0" />
    <PackageReference Include="MongoDB.Driver.Core" Version="2.30.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FinanceAPICore\FinanceAPICore.csproj" />
  </ItemGroup>

</Project>
