<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FinanceAPICore\FinanceAPICore.csproj" />
    <ProjectReference Include="..\FinanceAPIMongoDataService\FinanceAPIMongoDataService.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Datafeeds\Importers\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Coinbase" Version="6.0.1" />
    <PackageReference Include="Hangfire.Console" Version="1.4.3" />
    <PackageReference Include="Hangfire.Core" Version="1.8.15" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
    <PackageReference Include="RestSharp" Version="112.1.0" />
    <PackageReference Include="Serilog" Version="4.1.0" />
  </ItemGroup>

</Project>
