name: Pipeline
on: [push]

jobs:
  Build_Docker_Image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Docker build
        run: |
          cd src/FinanceAPI
          docker login docker.pkg.github.com -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
          docker build -t docker.pkg.github.com/benfl3713/finance-api/finance-api:latest .
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Publish
        if: github.ref == 'refs/heads/master'
        run: |
          docker push docker.pkg.github.com/benfl3713/finance-api/finance-api:latest
          docker tag docker.pkg.github.com/benfl3713/finance-api/finance-api:latest $DOCKER_USERNAME/finance-api
          docker push $DOCKER_USERNAME/finance-api
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
